# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18YwR4TDw-6AzKBsLOtTC4bNuTZEF8uxH
"""

import random

def tas_kagit_makas_Buse_Akyün():
    print("Buse Akyün Taş, Kağıt, Makas Oyununa Hoş Geldiniz!")
    print("Oyun kuralları: İlk iki turu kazanan, oyunu kazanır.")
    print("Seçenekler: Taş, Kağıt, Makas")
    print("Oyundan çıkmak için 'q' yazabilirsiniz.\n")

    while True:
        oyuncu_galibiyet = 0
        bilgisayar_galibiyet = 0
        tur_sayisi = 1

        while oyuncu_galibiyet < 2 and bilgisayar_galibiyet < 2:
            print(f"\n{tur_sayisi}. Tur")
            oyuncu_seçimi = input("Lütfen seçiminizi yapın (Taş, Kağıt, Makas): ").lower()

            if oyuncu_seçimi == 'q':
                print("Oyundan çıkılıyor.")
                return

            if oyuncu_seçimi not in ['taş', 'kağıt', 'makas']:
                print("Geçersiz seçim. Lütfen tekrar deneyin.")
                continue

            bilgisayar_seçimi = random.choice(['taş', 'kağıt', 'makas'])
            print(f"Bilgisayarın seçimi: {bilgisayar_seçimi}")

            if oyuncu_seçimi == bilgisayar_seçimi:
                print("Berabere!")
            elif (oyuncu_seçimi == "taş" and bilgisayar_seçimi == "makas") or \
                 (oyuncu_seçimi == "kağıt" and bilgisayar_seçimi == "taş") or \
                 (oyuncu_seçimi == "makas" and bilgisayar_seçimi == "kağıt"):
                print("Bu turu kazandınız!")
                oyuncu_galibiyet += 1
            else:
                print("Bu turu bilgisayar kazandı!")
                bilgisayar_galibiyet += 1

            tur_sayisi += 1

        if oyuncu_galibiyet == 2:
            print("\nTebrikler! Oyunu kazandınız!")
        else:
            print("\nBilgisayar oyunu kazandı.")

        # Tekrar oynama isteği
        devam_mi = input("Başka bir oyun oynamak ister misiniz? (Evet için 'e', Hayır için 'h'): ").lower()
        bilgisayar_devam = random.choice(['e', 'h'])

        if devam_mi == 'h' or bilgisayar_devam == 'h':
            print("Oyun sona erdi. Tekrar görüşmek üzere!")
            break
        else:
            print("Yeni bir oyun başlıyor!\n")

# Fonksiyonu çalıştırmak için
tas_kagit_makas_Buse_Akyün()